
##Docker -- Heroku itegration is throwing internal server errors for me so I used this to deploy to heroku: https://github.com/marketplace/actions/deploy-to-heroku

name: Release DevOps with Docker practise heroku version


on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "docker31" 
          heroku_email: "${{secrets.EMAIL}}"
          usedocker: true
